name: Matrix - Docker build and push to GCP Artifact Registry

on:
  push:
    branches:
      - main
      - github-action

env:
  GAR_LOCATION: us-east1
  REPOSITORY: cbdb-repo

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - name: almalinux
            version: '9'

          - name: debian
            version: '12'

    steps:
    - id: checkout
      name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate with Google Cloud'
      uses: 'google-github-actions/auth@v0.6.0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        token_format: 'access_token'

    - uses: 'docker/login-action@v1'
      name: 'Login to Artifact Registry'
      with:
        registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'

    - name: Get tag
      id: get-tag
      run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

    - id: docker-push-tagged
      name: Tag Docker image and push to Google Artifact Registry
      uses: docker/build-push-action@v2
      with:
        push: true
        context: "{{defaultContext}}:/containers/${{ matrix.os.name }}/${{ matrix.os.version }}"
        tags: |
             ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ env.REPOSITORY }}/cbdb-${{ matrix.os.name }}${{ matrix.os.version }}:${{ steps.get-tag.outputs.short_ref }}
             ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ env.REPOSITORY }}/cbdb-${{ matrix.os.name }}${{ matrix.os.version }}:latest
